// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCgf7Iyw907iyoIWjqsaNEyKPucjuimD8',
    appId: '1:1071687363327:web:96759a38448c5c7647faca',
    messagingSenderId: '1071687363327',
    projectId: 'sacekimmerkezi-85e99',
    authDomain: 'sacekimmerkezi-85e99.firebaseapp.com',
    storageBucket: 'sacekimmerkezi-85e99.firebasestorage.app',
    measurementId: 'G-3FBK88W4JW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmXyD0h7rlO1_UrEKyTzE8bzNFJ7zckFI',
    appId: '1:1071687363327:android:0442a0f8f3075ab647faca',
    messagingSenderId: '1071687363327',
    projectId: 'sacekimmerkezi-85e99',
    storageBucket: 'sacekimmerkezi-85e99.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0UQOzTsH19D23MhFT71fWonNhl0j1GMM',
    appId: '1:1071687363327:ios:3b301212fe6939d747faca',
    messagingSenderId: '1071687363327',
    projectId: 'sacekimmerkezi-85e99',
    storageBucket: 'sacekimmerkezi-85e99.firebasestorage.app',
    iosBundleId: 'com.hairclinic.sacEkimApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0UQOzTsH19D23MhFT71fWonNhl0j1GMM',
    appId: '1:1071687363327:ios:3b301212fe6939d747faca',
    messagingSenderId: '1071687363327',
    projectId: 'sacekimmerkezi-85e99',
    storageBucket: 'sacekimmerkezi-85e99.firebasestorage.app',
    iosBundleId: 'com.hairclinic.sacEkimApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    appId: '1:1071687363327:windows:XXXXXXXXXXXXXXXXXX',
    messagingSenderId: '1071687363327',
    projectId: 'sacekimmerkezi-85e99',
    authDomain: 'sacekimmerkezi-85e99.firebaseapp.com',
    storageBucket: 'sacekimmerkezi-85e99.firebasestorage.app',
  );
}